image:
  repository: mosesade/complete-devops-project
  tag: e18b705
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 2222
ingress:
  enabled: false
serviceAccount:
  enabled: false
autoscaling:
  enabled: false