---

name: Complete DevOps Project Pipeline

on:
  push:
    paths:
      - 'app.py'
      - '.github/workflows/ci.yaml'
    branches:
      - master

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Checks credentials leaks
        uses: gitleaks/gitleaks-action@v3
        env:
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set Short SHA
        run: |
          echo "SHORT_SHA=$(echo ${GITHUB_SHA} | cut -c1-7)" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -t mosesade/complete-devops-project:${{ env.SHORT_SHA }} .

      - name: Run security scan using Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: mosesade/complete-devops-project:${{ env.SHORT_SHA }}
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Login to Dockerhub
        run:  |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ vars.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Push to Dockerhub
        run:  |
          docker push mosesade/complete-devops-project:${{ env.SHORT_SHA }}

      # Optional: AWS ECR login and push (commented out)
      # - name: Configure AWS Credentials
      #  uses: aws-actions/configure-aws-credentials@v2
      #  with:
      #    aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #    aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: us-west-2
      #
      # - name: Login to AWS ECR
      #   id: ecr-login
      #   uses: aws-actions/amazon-ecr-login@v2
      #   run: |
      #     aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin <your_aws_account_id>.dkr.ecr.us-east-1.amazonaws.com
      # - name: Push to AWS ECR
      #   env:
      #     ECR_REGISTRY: <your_aws_account_id>.dkr.ecr.us-east-1.amazonaws.com/complete-devops-project
      #     ECR_REPOSITORY: <your_aws_account_id>.dkr.ecr.us-east-1.amazonaws.com/complete-devops-project
      #   run: |
      #     docker tag mosesade/complete-devops-project:${{ env.SHORT_SHA }} $ECR_REPOSITORY:${{ env.SHORT_SHA }}
      #     docker push $ECR_REPOSITORY:${{ env.SHORT_SHA }}

      - name: Configure Git Authours
        run: |
          git config --local user.email "moses.adelere@gmail.com"
          git config --local user.name  "Moses A."

      - name: Update Helm chart with image tag
        run: |
          sed -i "s/tag:.*/tag: ${{ env.SHORT_SHA }}/" ./complete-devops-project-time-printer/values.yaml
          git add ./complete-devops-project-time-printer/values.yaml
          git commit -m "updated image tag to ${{ env.SHORT_SHA }}"
          git push
